name: Validate conan-center-index/issues/27438

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-ffmpeg-conan-setup:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install self-contained Conan on Windows
        if: runner.os == 'Windows'
        run: |
          curl -sSL -o conan.zip https://github.com/conan-io/conan/releases/download/2.16.1/conan-2.16.1-windows-x86_64.zip
          powershell -Command "Expand-Archive -Path conan.zip -DestinationPath $env:USERPROFILE\conan-bin"
          echo "$env:USERPROFILE\conan-bin" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append

      - name: Install self-contained Conan on Linux
        id: install-self-contained-conan-linux
        if: runner.os == 'Linux'
        run: |
          wget -q -O $RUNNER_TEMP/conan.tgz https://github.com/conan-io/conan/releases/download/2.16.1/conan-2.16.1-linux-x86_64.tgz
          mkdir -p "$HOME/.local"
          tar -xzf "$RUNNER_TEMP/conan.tgz" -C "$HOME/.local"
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Detect Conan profile
        run: conan profile detect || true

      - name: Create package with regular build
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose

      - name: Add PKG_CONFIG_PATH as unix path style
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/pkgconfig
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose

      - name: Add PKG_CONFIG_PATH as forward slash path style
        env:
          PKG_CONFIG_PATH: C:/usr/lib/pkgconfig
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose

      - name: Add PKG_CONFIG_PATH as bask slash path style
        env:
          PKG_CONFIG_PATH: C:\usr\lib\pkgconfig
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose
