name: Validate conan-center-index/issues/27438

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-ffmpeg-conan-setup:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Conan
        uses: uilianries/setup-conan@fix-env

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Check python version
        run: python --version

      - name: Install dependencies
        run: conan install -r conancenter --requires=ffmpeg/7.1.1 --build="ffmpeg/*"

  build-ffmpeg-conan-install:
    runs-on: windows-2022
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          update-environment: false

      - name: Install Conan
        run: pipx install conan

      - name: Configure Conan profile
        run: conan profile detect

      - name: Install dependencies
        run: conan install -r conancenter --requires=ffmpeg/7.1.1 --build="ffmpeg/*"
