name: Validate conan-center-index/issues/27438

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-ffmpeg-conan-setup:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install self-contained Conan on Windows
        shell: bash
        id: install-self-contained-conan-windows
        if: runner.os == 'Windows'
        run: |
          conan_version=2.16.1
          curl -sSL -o $RUNNER_TEMP/conan.zip https://github.com/conan-io/conan/releases/download/${conan_version}/conan-${conan_version}-windows-x86_64.zip
          unzip -q "$RUNNER_TEMP/conan.zip" -d "$HOME/bin"
          echo "PATH=$HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Install self-contained Conan on Linux
        shell: bash
        id: install-self-contained-conan-linux
        if: runner.os == 'Linux'
        run: |
          conan_version=2.16.1
          wget -q -O $RUNNER_TEMP/conan.tgz https://github.com/conan-io/conan/releases/download/${conan_version}/conan-${conan_version}-linux-x86_64.tgz
          mkdir -p "$HOME/.local"
          tar -xzf "$RUNNER_TEMP/conan.tgz" -C "$HOME/.local"
          echo "PATH=$HOME/.local/bin:$PATH" >> $GITHUB_ENV

      - name: Detect Conan profile
        shell: bash
        id: detect-conan-profile
        run: |
          conan profile detect || true

      - name: Create package with regular build
        shell: bash
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose

      - name: Add PKG_CONFIG_PATH as unix path style
        shell: bash
        env:
          PKG_CONFIG_PATH: ${{ github.workspace }}/pkgconfig
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose

      - name: Add PKG_CONFIG_PATH as forward slash path style
        shell: bash
        env:
          PKG_CONFIG_PATH: C:/usr/lib/pkgconfig
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose

      - name: Add PKG_CONFIG_PATH as bask slash path style
        shell: bash
        env:
          PKG_CONFIG_PATH: C:\usr\lib\pkgconfig
        run: conan create . -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose
