name: Validate conan-center-index/issues/27438

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:

  build-ffmpeg-conan-setup:
    strategy:
      matrix:
        os: [ubuntu-22.04, windows-2022]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Conan
        uses: conan-io/setup-conan@v1

      - name: Check for installed conan
        shell: bash
        run: |
          which conan
          conan --version

      - name: Check python version
        run: python --version

      - name: Install ffmpeg package on Windows
        if: runner.os == 'Windows'
        continue-on-error: true
        run: conan install -r conancenter --requires=ffmpeg/7.1.1 -of output --build="ffmpeg/*"

      - name: Install ffmpeg package on Linux
        if: runner.os == 'Linux'
        continue-on-error: true
        run: conan install -r conancenter --requires=ffmpeg/7.1.1 -of output --build="ffmpeg/*" -c tools.build:verbosity=verbose -c tools.compilation:verbosity=verbose -c tools.system.package_manager:sudo=false -c tools.system.package_manager:mode=install -o "&:with_xcb=False" -o "&:with_xlib=False" -o "&:with_pulse=False"

      - name: Upload build folder to Github artifacts
        if: runner.os == 'Windows'
        uses: actions/upload-artifact@v4
        with:
          path: 'C:\Users\runneradmin\.conan2\p\b'
          name: ffmpeg-build-${{ matrix.os }}
